# No clear secrets in git. Ciphertext only; the in-cluster sealed-secrets
# controller unseals it into Secret studystack0-secrets (envFrom). Sealed (strict
# scope) against the dev cluster cert for namespace sdk-apps-dev.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: studystack0-secrets
  namespace: sdk-apps-dev
spec:
  encryptedData:
    INTERACTIVE_SECRET: AgBfKJbAnDTpmGkWIQO78pzCoEDAmoaqLceBHEd0ij5SpG7B0dbPXpFxLqtTJzOuIZegO0CDjW9tc3Ht7FcMzy3AkGLfUzNPnjs3itHSGgF8DH7xxYjYu1J07gULhE4TXCacszj7hnoveO7D96Va0gRVOqwoSAiUuABXzDEJsIB3rddHRXyXLt6uWCVD4ocDpamuS1fTysxKK6ZzJNJ9MqZC3E2dW/ohycNk3nNGOGVRcD+hESMMQJADGw7iA+bb5KO0BGS8cVr9ft1aeDiugqMAR3p/nLZ/blTESjrl9mcAaV4kvZ3biGOkb5XVTNlAxShHG1TXZ34dBBA+m3OFryqrjRTr1MrBBUFOnJoHqE428PRFj95NmMas/niDs+j2ePSwzLGWTjC64EBnIvjConnAfqZAJR7HQKi2RoRoFcQ9Wjx8f7eEEkmNDeCjVbXUxabCGYXbMxp4e5WvNGCkwJbaBq/Z3ThbU1nUSMbzRCCXHWrVB+yJ6gVQH6z8CGNtxsNsC0Tp8xfobM4gb5qfinaOYdnBtC1tv/E7cZtdjXeO4aftUHV2ajI4umzOgMXFQiWHmlU7y6BYI+Amh7aYMWp/cYaKO6qqVj6aF5qBTUFJo3b7PAjD6A68Cuove8IK9K9cGV4KWflZx1ynHdCiBOSCMjbZrctK9Osk1tz6fXGpVlLiKZdvh5eiO6vvIMo9P16+aXKKfW93ZkcyXTTA3Fx3NHiQO1+Ic/+bq1xbyCh1OEHgMtgx4peOj5LfIufLB2A=
  template:
    metadata:
      name: studystack0-secrets
      namespace: sdk-apps-dev
    type: Opaque
